Repository RescueOnWheels/Nervi, pull requests merged in 2018-10, with the labels that each got.

#5 Directory structure
  distanceSensor.js
  index.js
  lib/nervi.js
  lib/servo.js
Labels: Type: Enhancement

#11 Added wheel encoder
  .eslintrc.js
  .npmrc
  .travis.yml
  index.js
  lib/nervi.js
  lib/rotary.js
  lib/servo.js
  package-lock.json
  package.json
  renovate.json
Labels: Type: Enhancement

#15 Reworked Nervi structure.
  README.md
  lib/nervi.js
  package.json
Labels: Type: Enhancement

#16 Added HC-SR04 support
  lib/nervi.js
  lib/rotary.js
  lib/ultrasonic.js
Labels: Type: Enhancement

#14 Added CameraMount class.
  lib/cameraMount.js
  lib/servo.js
Labels: Type: Enhancement

#22 classfix
  lib/cameraMount.js
  lib/nervi.js
Labels: Type: Enhancement

#23 Bug/fix
  lib/cameraMount.js
  lib/rotary.js
  lib/servo.js
Labels: Type: Bug

#24 Changed function name
  lib/nervi.js
Labels: Type: Maintenance

#27 Added mock of PIGPIO.
  .eslintrc.js
  .eslintrc.yml
  .travis.yml
  lib/interfaces/pigpio.js
  lib/interfaces/pigpio.mock.js
  lib/rotary.js
  package.json
  test/mocha.opts
  test/mock/index.js
  test/mock/rotary.test.js
  test/real/index.js
  test/test.js
Labels: Type: Enhancement

#29 Add compass to nervi
  lib/nervi.js
Labels: Type: Enhancement

#30 yes
  lib/compass.js
  lib/nervi.js
Labels: Type: Enhancement

#31 here we go again
  lib/compass.js
Labels: Type: Bug

#33 onAlert emit data fix
  lib/ultrasonic.js
Labels: Type: Enhancement

#35 Fixed lower limit of servo.
  .eslintrc.yml
  lib/cameraMount.js
  lib/helpers/normalize.js
  lib/interfaces/pigpio.js
  lib/interfaces/pigpio.mock.js
  lib/servo.js
  lib/ultrasonic.js
  test/mock/index.js
  test/mock/ultrasonic.test.js
Labels: Type: Bug
