Repository RescueOnWheels/Nervi, pull requests merged in 2018-11, with the labels that each got.

#38 Removed compass code and improved tests.
  lib/compass.js
  lib/interfaces/pigpio.mock.js
  lib/nervi.js
  lib/servo.js
  package.json
  test/mock/cameraMount.test.js
  test/mock/helpers/normalize.test.js
  test/mock/index.js
  test/mock/rotary.test.js
  test/mock/servo.test.js
  test/mock/ultrasonic.test.js
Labels: Type: Bug

#41 Improved rotary/wheel encoder.
  lib/rotary.js
  test/mock/rotary.test.js
Labels: Type: Enhancement

#45 Reset cameramount at startup
  lib/cameraMount.js
Labels: Type: Enhancement

#52 Cleanup
  lib/cameraMount.js
  lib/compass.js
  lib/interfaces/hmc5883l.js
  lib/interfaces/hmc5883l.mock.js
  lib/nervi.js
  lib/rotary.js
  lib/ultrasonic.js
  package.json
  test/mock/compass.test.js
  test/mock/index.js
  test/mock/rotary.test.js
Labels: Type: Maintenance
